name: CI/CD Lab

on:
  push:
    branches:
      - lab-3
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a simple command
        run: echo "Lab3-ci/cd"

      - name: Gather System Information
        run: |
          echo "CPU Info: $(lscpu)"
          echo "Runner OS: $RUNNER_OS"
          echo "Memory Info: $(free -h)"
          echo "Network Info:  $(ip addr show)"
          echo "Disk Info: $(df -h)"
