name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v2

      - name: Вывод сообщения
        run: echo "Этот workflow был запущен вручную!"

      - name: Сбор информации о системе
        run: |
          echo "Информация о системе:"
          uname -a
          echo "Версия Python:"
          python --version
