name: Network Analysis

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  traceroute_and_dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install traceroute
        run: |
          sudo apt-get update
          sudo apt-get install -y traceroute

      - name: Traceroute to github.com
        run: |
          echo "=== Traceroute ==="
          traceroute github.com || echo "Error occurred during Traceroute step"

      - name: DNS Resolution for github.com
        run: |
          echo "=== DNS Resolution ==="
          dig github.com || echo "Error occurred during DNS Resolution step"

  packet_capture:
    runs-on: ubuntu-latest
    needs: traceroute_and_dns
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Capture DNS Traffic
        run: |
          echo "=== Generating DNS Traffic ==="
          dig github.com || echo "Error occurred during DNS Traffic Generation step"
          
          echo "=== Packet Capture ==="
          sudo timeout 10 tcpdump -c 5 -i any 'port 53' -nn || echo "Error occurred during Packet Capture step"
          
  reverse_dns_lookup:
    runs-on: ubuntu-latest
    needs: packet_capture
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dnsutils
        run: |
          sudo apt-get update
          sudo apt-get install -y dnsutils

      - name: Reverse DNS Lookup for 8.8.4.4
        run: |
          echo "=== Reverse DNS Lookup ==="
          dig -x 8.8.4.4 || echo "Error occurred during Reverse DNS Lookup for 8.8.4.4 step"

      - name: Reverse DNS Lookup for 1.1.1.1
        run: |
          dig -x 1.1.1.1 || echo "Error occurred during Reverse DNS Lookup for 1.1.1.1 step"
